### ISSUE TITLE
migrate database error

### ISSUE THREAD

**Issue by archonwang** [tastapod/redmine_blocks_layout#20]
@tastapod , @eckucukoglu 
when I installed the plungin with migrating database, it occured an error. Please check it. Thanks so much.

```
Migrating redmine_blocks_layout (Blocks Layout plugin)...
== 1 CreateTables: migrating ==================================================
-- create_table(:overview_blocks)
   -> 0.0305s
-- create_table(:home_blocks)
   -> 0.0028s
rake aborted!
An error has occurred, all later migrations canceled:

Couldn't find Project with 'id'=all/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:444:in `find_one'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:423:in `find_with_ids'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/relation/finder_methods.rb:71:in `find'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:3:in `find'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/core.rb:130:in `find'
/opt/redmine-3.3/app/models/project.rb:310:in `find'
/opt/redmine-3.3/plugins/redmine_blocks_layout/db/migrate/001_create_tables.rb:12:in `up'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:571:in `up'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:611:in `exec_migration'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1046:in `ddl_transaction'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
/usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
/opt/redmine-3.3/lib/redmine/plugin.rb:481:in `migrate_plugin'
/opt/redmine-3.3/lib/redmine/plugin.rb:453:in `migrate'
/opt/redmine-3.3/lib/redmine/plugin.rb:467:in `block in migrate'
/opt/redmine-3.3/lib/redmine/plugin.rb:466:in `each'
/opt/redmine-3.3/lib/redmine/plugin.rb:466:in `migrate'
/opt/redmine-3.3/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)

```

my environment is 
> Environment:
>   Redmine version                3.3.0.stable.15748
>   Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
>   Rails version                  4.2.7.1
>   Environment                    production
>   Database adapter               Mysql2

**Comment by tastapod** [comment]
I’m not actively maintaining this plugin any more. If you figure this out please post a pull request and I will merge it for you.

**Comment by eckucukoglu** [comment]
hi @archonwang, @tastapod ,

This bug happens because of find(:all) method calls deprecated. 
Check ref: http://stackoverflow.com/questions/15098961/findfirst-and-findall-are-deprecated

I have sent a patch for that. :palm_tree:

**Comment by archonwang** [comment]
@eckucukoglu , Thanks.

I will test the branch later.

**Comment by archonwang** [comment]
@eckucukoglu , Nice, it works. Thanks.
